In [559]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

In [560]:
#Data
df = pd.read_csv("./student.csv")

# เช็คว่าช้อมูลนี้ มี Missing อยู่ ได้จาก
df.isnull().sum()

รหัสนักศึกษา               0
ชื่อ                       1
อายุ                       3
เพศ                        2
คณะ                        2
GPA                        2
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
dtype: int64

##Dropna

In [561]:
# แสดงข้อมูลก่อนลบ
print("ก่อนลบ")
df
#สังเกตุได้ว่า ข้อมูลที่ 10 อายุ เพศ คณะ ส่วนสูง ชั่วโมงเรียน จะเป็นค่า NaN จะใช้ ฟังก็ชั่น Dropna ซึ่งเป็นการ ลบ ทั้ง Row

ก่อนลบ

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

สังเกตุได้ว่า ข้อมูลที่ 10 อายุ เพศ คณะ ส่วนสูง ชั่วโมงเรียน จะเป็นค่า NaN จะใช้ ฟังก็ชั่น Dropna ซึ่งเป็นการ ลบ ทั้ง Row

In [562]:
df_clean_dropna = df.dropna()
#df_clean_dropna

#ข้อมูลที่เป็น Nan จะหายไปแล้ว เช็คได้จาก
df_clean_dropna

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24

##Mean Replcing

In [563]:
df.isnull().sum()
#สังเกตได้ว่า คอลัมน์ที่เป็นตัวเลข และสามารถหาค่าเฉลี่ยได้ คืออ อายุ เกรด ส่วนสูง น้ำหนัก และชั่วโมงเรียนต่อสัปดาห์

รหัสนักศึกษา               0
ชื่อ                       1
อายุ                       3
เพศ                        2
คณะ                        2
GPA                        2
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
dtype: int64

mean replace คือแทนค่าที่มี missing ด้วยค่าเฉลี่ย ด้วยฟังก์ชั่น fillna

In [564]:
#หาค่าเฉลี่ยอายุ ส่วนสูง น้ำหนัก และชั่วโมงเรียนต่อสัปดาห์
mean_age = df['อายุ'].mean()
mean_grade = df['GPA'].mean()
mean_height = df['ส่วนสูง_cm'].mean()
mean_weight = df['น้ำหนัก_kg'].mean()
mean_hour = df['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()

#แทนค่าที่มี missing ด้วยค่าเฉลี่ย ด้วยฟังก์ชั่น fillna
df['อายุ'].fillna(mean_age, inplace=True)
df['GPA'].fillna(mean_grade,inplace=True)
df['ส่วนสูง_cm'].fillna(mean_height, inplace=True)
df['น้ำหนัก_kg'].fillna(mean_weight, inplace=True)
df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hour, inplace=True)

df
#จะได้ว่า ค่า Missing value ที่เป็นตัวเลข ได้ถูกแก้ไขเร้บร้อย

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06

##Mode

In [565]:
#ใช้ค่าที่พบบ่อยที่สุด (mode) ที่สามาารถแก้ได้ คือ คณะ และเพศ
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06

ใช้ค่าที่พบบ่อยที่สุด (mode) ที่สามาารถแก้ได้ คือ คณะ และเพศ

In [566]:
#แทนค่าที่เป้น Missing Value ของ เพศ และคณะ ด้วย ค่าที่ซ้ำที่สุด ด้วยฟังก์ชั่น mode
df['เพศ'].fillna(df['เพศ'].mode()[0], inplace=True)
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

print("เพศส่วนใหญ่คือ: ",df['เพศ'].mode()[0]) #ปรั้นว่า เพศส่วนใหญ่คือ
#แล้วเช็คว่ามี Missing Value ไหม เช่น Row 10 ที่เพศเป็น nan
df

เพศส่วนใหญ่คือ:  ชาย

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,ชาย,Science,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,Science,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,ชาย,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06

##Standarization (ข้อมูลที่เป็นมาตรฐาน )

In [567]:
#คือข้อมูลบางข้อมูล เช่น เพศ มีการใส่ M,Male,ชาย มา ไม่เหมือนกัน ดังนั้น จึงต้องแก้
df
#ในที่นี้มี เพศ และ คณะ

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,ชาย,Science,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,Science,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,ชาย,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06

คือข้อมูลบางข้อมูล เช่น เพศ มีการใส่ M,Male,ชาย มา ไม่เหมือนกัน ดังนั้น จึงต้องแก้ ด้วยการสร้าง เมธอด ขึ้นมากรอง

In [568]:
#คณะ มีข้อมูลอะไรบ้างd
print(df['คณะ'])
print(df['เพศ'])

0        วิทยาศาสตร์
1              วิทย์
2            Science
3     คณะวิทยาศาสตร์
4              วิศวะ
5        Engineering
6           วิศวกรรม
7         ศิลปศาสตร์
8               Arts
9              ศิลป์
10           Science
11             วิทย์
12             วิศวฯ
13      Liberal Arts
14               Sci
15       วิทยาศาสตร์
16    วิศวกรรมศาสตร์
17           Science
18        ศิลปศาสตร์
19           Science
Name: คณะ, dtype: object
0        ชาย
1       หญิง
2       Male
3          ช
4          ญ
5        ชาย
6       หญิง
7          F
8          M
9       หญิง
10       ชาย
11       ชาย
12      หญิง
13       ชาย
14    Female
15         ช
16         ญ
17      หญิง
18       ชาย
19       ชาย
Name: เพศ, dtype: object

จะมีคณะ วิทยาศาสตร์ - วิทย์ , Science ,Sci
 วิศวกรรมศาสตร์ - วิศวกรรม,วิศวะ ,Engineering ,วิศวฯ
 ศิลปศาสตร์ - Arts,ศิลป์ ,Liberal Arts
 และ
 เพศ ชาย - Male ,M,ช
 หญิง - Female,F,ญ

In [569]:
#สร้าง ฟังก์ชั่นมากำกับคำ
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์','Sci']: #วิทยาศาสตร์ - วิทย์ , Science ,Sci
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts','Liberal Arts']:#ศิลปศาสตร์ - Arts,ศิลป์ ,Liberal Arts
        return 'ศิลปศาสตร์'
    elif name in ['วิศวกรรมศาสตร์','วิศวกรรม','วิศวะ','Engineering','วิศวฯ']: #วิศวกรรมศาสตร์ - วิศวกรรม,วิศวะ ,Engineering ,วิศวฯ
        return 'วิศวกรรมศาสตร์'
    else:
        return name

def standardize_gender(name):
    if name in ['ชาย','Male','M','ช']:
        return 'ชาย'
    elif name in ['หญิง','Female','F','ญ']:
        return 'หญิง'
    else:
        return name

#แทนที่ คณะแบบเียนผิดๆถูกๆ
df['คณะ'] = df['คณะ'].apply(standardize_faculty)
df['เพศ'] = df['เพศ'].apply(standardize_gender)
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-06

##Abnormaly Value

In [570]:
df
#ในที่นี่ เห็นอายุ และ gpa

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-06

คือการจัดการค่าท่ีมาก น้อย ผิดปกติ ในที่นี้มี อายุ และ เกรด อายุ จะใช้การหา Quantile เป็นขอบเขต ส่วน เกรด จะใช้ 1 และ 4 เป็นขอบเขต

In [571]:
#Age
Q1_Age = df['อายุ'].quantile(0.25)
Q3_Age = df['อายุ'].quantile(0.75)
IQR_Age = Q3_Age - Q1_Age
#ขอบเขตของ อายุ
lower_bound_age = Q1_Age - 1.5 * IQR_Age
upper_bound_age = Q3_Age + 1.5 * IQR_Age
print(lower_bound_age,upper_bound_age)

#gpa
lower_bound_gpa = 1
upper_bound_gpa = 4
print(lower_bound_gpa,upper_bound_gpa)

16.625 25.625
1 4

In [572]:
#กรองค่าผิดปกติออก ของอายุ และเกรด
df_no_outliers = df[((df['อายุ'] >= lower_bound_age) & (df['อายุ'] <= upper_bound_age )) & ((df['GPA'] >= 1) & (df['GPA'] <= 4))]

#df_no_outliers = df_abnormal[(df_abnormal['GPA'] >= lower_bound_gpa) & (df_abnormal['GPA'] <= upper_bound_gpa)]
df = df_no_outliers
#ข้อมูลที่ อายุ เกินไป กับ เกรด น้อยกว่า 1 มากกว่า 4 จะถูกตัดไป
df_no_outliers

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.0,65.000000,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.0,58.000000,20.0,2024-02-05
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.000000,30.0,2024-01-27
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.0,82.000000,18.0,2024-01-23
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.0,55.000000,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.0,60.000000,28.0,2024-01-03
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.0,63.611111,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.000000,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.0,54.000000,19.0,2024-01-08
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.0,56.000000,26.0,2024-02-06
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.0,78.000000,14.0,2024-01-20
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.000000,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.230000,161.0,50.000000,27.0,2024-01-08
19,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.450000,168.0,64.000000,23.0,2024-01-06

##ขั้นสุดท้าย แทนที่ค่าเป็นไม่ระบุ,Unknown
จะเหลือ คอลั่มน์ ชื่อ ที่ยังมี Error และทศนิยมที่เยอะมาก ปรับให้เหลือ .2 โดยฟังก์ชั่น round(2)

In [573]:
df.isnull().sum()
#จะเหลือ คอลั่มน์ ชื่อ ที่ยังมี Error
df['ชื่อ'].fillna('ไม่ระบุ', inplace=True)
df = df.round(2)
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.00,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.00,20.0,2024-02-05
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.00,30.0,2024-01-27
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.00,18.0,2024-01-23
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.00,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.00,28.0,2024-01-03
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.25,171.0,63.61,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.00,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.00,19.0,2024-01-08
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.00,26.0,2024-02-06
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.00,14.0,2024-01-20
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.00,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.23,161.0,50.00,27.0,2024-01-08
19,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.45,168.0,64.00,23.0,2024-01-06

In [574]:
#เช็ค Missing Value
df.isnull().sum().sum()

np.int64(0)

##BMI

In [576]:
# สร้าง BMI
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_cm']/100)**2
df['สุขภาพ'] = pd.cut(df['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,BMI,สุขภาพ
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.00,15.0,2024-01-23,22.491349,ปกติ
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.00,20.0,2024-02-05,21.303949,ปกติ
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.00,30.0,2024-01-27,20.312500,ปกติ
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.00,18.0,2024-01-23,25.308642,อ้วน
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.00,22.0,2024-02-11,20.700817,ปกติ
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.00,28.0,2024-01-03,21.513859,ปกติ
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.25,171.0,63.61,16.0,2023-12-26,21.753702,ปกติ
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.00,24.0,2023-12-26,25.209201,อ้วน
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.00,19.0,2024-01-08,20.077335,ปกติ
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.00,26.0,2024-02-06,21.338211,ปกติ
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.00,14.0,2024-01-20,26.061679,อ้วน
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.00,21.0,2024-01-24,22.499637,ปกติ
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.23,161.0,50.00,27.0,2024-01-08,19.289379,ปกติ
19,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.45,168.0,64.00,23.0,2024-01-06,22.675737,ปกติ